version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: node:10
        steps:
            - checkout
            - restore_cache:
                  key: node-modules-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: yarn build
            - save_cache:
                  key: node-modules-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules

    deploy:
        working_directory: ~/project
        docker:
            - image: node:10
        steps:
            - checkout
            - restore_cache:
                  key: node-modules-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: yarn deploy --token $ZEIT_TOKEN

            - save_cache:
                  key: node-modules-{{ checksum "yarn.lock" }}
                  paths:
                      - ./node_modules

workflows:
    version: 2
    node:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - master

            - deploy:
                  filters:
                      branches:
                          only:
                              - master
